ors:
  engine:
    source_file: /home/ors/files/sweden-latest.osm.pbf
    elevation:
      preprocessed: false
      cache_clear: true
      provider: multi
      cache_path: /home/ors/elevation_cache
    profiles:
      cycling-electric:
        enabled: true
        profile: cycling-electric
        elevation: false
        encoder_options:
          consider_elevation: false
          turn_costs: true
          block_fords: false